# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b6891ed6143e5396996c729296a7869939ca78935b37c4b28618987b2bb40c15c3e90defa78e224b9f80df0dc2a494b7644200085eaef0b1cb071c6af6be370

test:
  secret_key_base: bc1508705e6367a10f7f8c7c0dc3659989f15520749395232eb0bc883a40263f02127cc973a4ce62b00be4d27b239c88a4e9ad68c680e746ece47a8dbc11665b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
